### ISSUE TITLE
🐛Cannot read property 'trim' of undefined at parseAsV2()

### ISSUE THREAD

**Issue by alexanderkasten** [atlas-engine/RuntimeDomain.LoggingApi#2]
## Description

Wenn ich die Inspect Ansicht des Studios öffne und auf den LogViewer navigiere bekomme ich keine Logs angezeigt. 

Ich bekomme in den AE logs folgenden Fehler:

```
2020-03-13T09:08:56.838Z - info: [http_extension:error_handler] 500 TypeError: Cannot read property 'trim' of undefined
    at parseAsV2 (/Users/alexanderkasten/Documents/GitHub/AtlasEngine/AtlasEngine.FullstackServer/node_modules/@atlas-engine/logging.repository.file_system/dist/commonjs/adapter/parser/deprecated/process_model_log_parser.js:35:48)
    at Object.parseProcessModelLog (/Users/alexanderkasten/Documents/GitHub/AtlasEngine/AtlasEngine.FullstackServer/node_modules/@atlas-engine/logging.repository.file_system/dist/commonjs/adapter/parser/deprecated/process_model_log_parser.js:13:16)
    at Object.parseDeprecatedLogEntry (/Users/alexanderkasten/Documents/GitHub/AtlasEngine/AtlasEngine.FullstackServer/node_modules/@atlas-engine/logging.repository.file_system/dist/commonjs/adapter/parser/deprecated/parser.js:9:38)
    at parseLogEntry (/Users/alexanderkasten/Documents/GitHub/AtlasEngine/AtlasEngine.FullstackServer/node_modules/@atlas-engine/logging.repository.file_system/dist/commonjs/adapter/parser/parser.js:11:20)
    at Array.map (<anonymous>)
    at Object.readAndParseFile (/Users/alexanderkasten/Documents/GitHub/AtlasEngine/AtlasEngine.FullstackServer/node_modules/@atlas-engine/logging.repository.file_system/dist/commonjs/adapter/file_system_adapter.js:59:46)
    at LoggingRepository.readLogForProcessModel (/Users/alexanderkasten/Documents/GitHub/AtlasEngine/AtlasEngine.FullstackServer/node_modules/@atlas-engine/logging.repository.file_system/dist/commonjs/logging_repository.js:18:40)
    at LoggingService.readLogForProcessModel (/Users/alexanderkasten/Documents/GitHub/AtlasEngine/AtlasEngine.FullstackServer/node_modules/@atlas-engine/logging.service/dist/commonjs/logging_service.js:8:51)
    at LoggingRepository.getProcessModelLog (/Users/alexanderkasten/Documents/GitHub/AtlasEngine/AtlasEngine.FullstackServer/node_modules/@atlas-engine/admin_domain.repository.embedded/dist/commonjs/logging_repository.js:8:43)
    at LoggingService.getProcessInstanceLog (/Users/alexanderkasten/Documents/GitHub/AtlasEngine/AtlasEngine.FullstackServer/node_modules/@atlas-engine/admin_domain.services/dist/commonjs/logging_service.js:17:54)
    at LoggingProxyService.getProcessInstanceLog (/Users/alexanderkasten/Documents/GitHub/AtlasEngine/AtlasEngine.FullstackServer/node_modules/@atlas-engine/process_engine_proxy/dist/commonjs/management_api/proxy_services/logging_proxy_service.js:22:51)
    at LoggingController.getProcessInstanceLog (/Users/alexanderkasten/Documents/GitHub/AtlasEngine/AtlasEngine.FullstackServer/node_modules/@atlas-engine/process_engine_proxy/dist/commonjs/management_api/endpoints/logging/logging_controller.js:23:50)
    at /Users/alexanderkasten/Documents/GitHub/AtlasEngine/AtlasEngine.FullstackServer/node_modules/async-middleware/dist/index.js:18:23
    at Layer.handle [as handle_request] (/Users/alexanderkasten/Documents/GitHub/AtlasEngine/AtlasEngine.FullstackServer/node_modules/express/lib/router/layer.js:95:5)
    at next (/Users/alexanderkasten/Documents/GitHub/AtlasEngine/AtlasEngine.FullstackServer/node_modules/express/lib/router/route.js:137:13)
    at Route.dispatch (/Users/alexanderkasten/Documents/GitHub/AtlasEngine/AtlasEngine.FullstackServer/node_modules/express/lib/router/route.js:112:3)
    at Layer.handle [as handle_request] (/Users/alexanderkasten/Documents/GitHub/AtlasEngine/AtlasEngine.FullstackServer/node_modules/express/lib/router/layer.js:95:5)
    at /Users/alexanderkasten/Documents/GitHub/AtlasEngine/AtlasEngine.FullstackServer/node_modules/express/lib/router/index.js:281:22
    at param (/Users/alexanderkasten/Documents/GitHub/AtlasEngine/AtlasEngine.FullstackServer/node_modules/express/lib/router/index.js:354:14)
    at param (/Users/alexanderkasten/Documents/GitHub/AtlasEngine/AtlasEngine.FullstackServer/node_modules/express/lib/router/index.js:365:14)
    at param (/Users/alexanderkasten/Documents/GitHub/AtlasEngine/AtlasEngine.FullstackServer/node_modules/express/lib/router/index.js:365:14)
    at Function.process_params (/Users/alexanderkasten/Documents/GitHub/AtlasEngine/AtlasEngine.FullstackServer/node_modules/express/lib/router/index.js:410:3)
```

Der ist zurückzuführen auf diese Stelle:

https://github.com/atlas-engine/RuntimeDomain.LoggingApi/blob/develop/logging.repository.file_system/src/adapter/parser/deprecated/process_model_log_parser.ts#L44

## Reproduction

- Prozess mit Fehlschlagendem ScriptTask erstellen
- deployen auf die frische AE
- starten
- im LET auf den Fehlgeschlagenen Task klicken
- keine Logs im Logviewer sehen

**Comment by ElRaptorus** [comment]
Fixed in https://github.com/atlas-engine/RuntimeDomain.LoggingApi/commit/841c3ce369d233ae251f320efb30785eaa0847a6
